### ISSUE TITLE
[BUG] [v1.04 & v1.05] NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kus** [ssypchenko/cs2-gungame#8]
`v1.0.3` works, `v1.04` & `v1.05` I get the same error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GunGame.Stats.StatsManager.GetNumberOfWinners() in /Users/sergeysypchenko/css-publish/GG2/gungame_stats.cs:line 484
   at GunGame.GunGame.StatsLoadRank() in /Users/sergeysypchenko/css-publish/GG2/gg2.cs:line 3044
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Looks like it's this function https://github.com/ssypchenko/cs2-gungame/blob/e14bfdedc03be0d738d3afe03edd823a0da32a80/gungame_stats.cs#L460

I'm using SQLite and the SQLite database exists and has data and is working in v1.0.3.

```
/home/steam/cs2/game/csgo/cfg# cat gungame-db.json 
{
  "DatabaseType": "SQLite",
  "DatabaseFilePath": "/csgo/cfg/gungame-db.sqlite"
}
```

```
/home/steam/cs2/game/csgo/cfg# cat gungame-db.sqlite 
[P++Ytablesqlite_sequencesqlite_sequenceCREATE TABLE sqlite_sequence(name,seq)?11?1tablegungame_playerdatagungame_playerdataCREATE TABLE gungame_playerdata (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        wins INTEGER NOT NULL DEFAULT 0,
                        authid TEXT NOT NULL DEFAULT '0',
                        name TEXT NOT NULL DEFAULT '0',
                        timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        sound INTEGER NOT NULL DEFAULT 1,
                        UNIQUE (authid)
???f'?/3        76561198053720175KegZ2024-01-20 09:10:05/13rdata76561199085877410LessStressBuilding2024-01-20 09:14:16/3   76561197989617744Ayro2024-01-20 09:04:417 /%76561198806908843Def Syndrome2024-01-20 09:04:35.   /76561197960377828Kus2024-01-20 09:12:59
??1gungame_playerdata
```

**Comment by ssypchenko** [comment]
> GetNumberOfWinners

I think I know the reason for this problem I use MySql and it works for me, but maybe SQLite works another way. 
I fixed that part and I will post the new release soon with the working translation. I hope it will fix that problem. I'll test with SQLite before posting.

**Comment by kus** [comment]
@ssypchenko great, thanks.

When you push a release just @ mention me here and I'll test it too on my end and let you know if it's working.

**Comment by ssypchenko** [comment]
> When you push a release just @ mention me here and I'll test it too on my end and let you know if it's working.

@kus  - I tested the plugin with SQLite myself. It works. Please test it on your side.

**Comment by kus** [comment]
@ssypchenko I'm still getting the same error.

The server is running Ubuntu 20.04, no one is on it. I start the server with no mods loaded, then run `[exec gg](https://github.com/kus/cs2-modded-server/blob/stage/game/csgo/cfg/gg.cfg)` to load GunGame (it's a [multi mod server](https://github.com/kus/cs2-modded-server)).

Here is a more complete log.

```
exec gg
02:14:32 [INFO] (cssharp:PluginContext) Loading plugin GG2
[GunGame_Stats] ******* StatsManager: Failed to load database configuration from
02:14:32 [INFO] (plugin:CS2_GunGame) [GunGame_Stats] ******* StatsManager: Failed to load database configuration from
[GunGame_Online - FATAL] InitializeDatabaseConnection: Database connection error: Object reference not set to an instance of an object., working without online reports
02:14:32 [INFO] (plugin:CS2_GunGame) [GUNGAME] GG Start, version v1.0.6
02:14:32 [INFO] (cssharp:PluginContext) Finished loading plugin CS2_GunGame
"SourceTV<0><BOT><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 51.72 
[GUNGAME]********* Event Round Start
02:14:32 [INFO] (plugin:CS2_GunGame) [GUNGAME]********* Event Round Start
[GunGame]********** Start WarmupRound
CHostStateMgr::QueueNewRequest( Changelevel (aim_ag_texture_jungle), 3 )
SV:  CNetworkServerService::StartChangeLevel( (no landmark) )
HostStateRequest::Start(HSR_GAME):  loop(levelload) id(3) addons(3095778105) desc(Changelevel (aim_ag_texture_jungle))
SwitchToLoop levelload requested:  id [3] addons [3095778105]
SourceTV[0] shutting down (non-relay) due to server disconnecting game.
CHLTVServer::Shutdown
02:14:33 [INFO] (plugin:CS2_GunGame) [GUNGAME] ************ Error: Can't find player slot 0 in playerMap.
SV:  Level loading started for 'aim_ag_texture_jungle'
02:14:33 [INFO] (plugin:CS2_GunGame) [GunGame] map aim_ag_texture_jungle loaded
[GunGame_Stats - FATAL] GetNumberOfWinners ******* An error occurred: Object reference not set to an instance of an object.
[GunGame]********** Start WarmupRound
System.NullReferenceException: Object reference not set to an instance of an object.
   at GunGame.Stats.StatsManager.GetNumberOfWinners() in /Users/sergeysypchenko/css-publish/GG2/gungame_stats.cs:line 645
   at GunGame.GunGame.StatsLoadRank() in /Users/sergeysypchenko/css-publish/GG2/gg2.cs:line 3293
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Here is the [commit](https://github.com/kus/cs2-modded-server/commit/94917f7677c4e8044253d101047a597f9951e579) where I upgraded to v1.0.6.

I added `"GeoDatabaseFilePath": "/csgo/cfg/GeoLite2-Country.mmdb"` to the `gungame-db.json` file and changed `"DatabaseFilePath"` to `"/csgo/cfg/gungame-db-v106.sqlite"` so it would create a new database.

It didn't create the new SQLite database either.

And as I said in the original message `v1.0.3` works.

**Comment by kus** [comment]
And here is the log when I revert back to `v1.0.3`. Same conditions, empty server, GunGame loads fine and is active:

```
] exec gg
02:30:44 [INFO] (cssharp:PluginContext) Loading plugin GG2
02:30:44 [INFO] (plugin:CS2_GunGame) [GUNGAME] GG Start, version v1.0.3
02:30:44 [INFO] (cssharp:PluginContext) Finished loading plugin CS2_GunGame
"SourceTV<0><BOT><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 12.62 
[GUNGAME]********* Event Round Start
[GunGame] Start WarmupRound
CHostStateMgr::QueueNewRequest( Changelevel (aim_ag_texture_jungle), 3 )
SV:  CNetworkServerService::StartChangeLevel( (no landmark) )
HostStateRequest::Start(HSR_GAME):  loop(levelload) id(3) addons(3095778105) desc(Changelevel (aim_ag_texture_jungle))
SwitchToLoop levelload requested:  id [3] addons [3095778105]
SourceTV[0] shutting down (non-relay) due to server disconnecting game.
CHLTVServer::Shutdown
SV:  Level loading started for 'aim_ag_texture_jungle'
[GunGame] Start WarmupRound
SV:  Spawn Server: aim_ag_texture_jungle
Created physics for aim_ag_texture_jungle
HLTV:maxplayers set to 32
Network socket 'hltv' opened on port 27020
Starting SourceTV server listening on port 27020, type non-relay
ClientPutInServer create new player controller [SourceTV]
Host activate: Changelevel (aim_ag_texture_jungle)
SourceTV[0] broadcast active.
"SourceTV<0><BOT><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 1.38 
[GUNGAME]********* Event Round Start
"SourceTV<0><BOT><Unassigned>" OnPreResetRound => CTMDBG, team 0  will switch 0 3.39 
[GUNGAME]********* Event Round Start

] status
Server:  Running [X.X.X.X:27015]
Client:  Disconnected
----- Status -----
@ Current  :  game
source   : console
hostname : shipREKT GunGame +Deathmatch +Turbo
spawn    : 3
version  : 1.39.8.5/13985 9842 secure  public
steamid  : [G:1:3335281] (85568392923374705)
udp/ip   : X.X.X.X:27015 (public X.X.X.X:27015)
os/type  : Linux dedicated
sourcetv[0] : X.X.X.X:27020 (public X.X.X.X:27020) delay 30.0s
players  : 0 humans, 1 bots (0 max) (not hibernating) (unreserved)
---------spawngroups----
loaded spawngroup(  1)  : SV:  [1: aim_ag_texture_jungle | main lump | mapload]
---------players--------
  id     time ping loss      state   rate adr name
   0      BOT    0    0     active      0 'SourceTV'
#end
--- SourceTV[0] Status ---
Online 00:09, FPS 63.9, Version 9842 (Linux)
Master "SourceTV", delay 30, frames 633 / ticks 633
Game Time 00:01, Mod "csgo", Map "aim_ag_texture_jungle"
Local IP X.X.X.X:27020, KB/sec In 0.0, Out 0.0
Local Slots 64, Spectators 0, Proxies 0
Total Slots 64, Spectators 0, Proxies 0
# userid name uniqueid connected ping loss state rate adr
#end
```

**Comment by ssypchenko** [comment]
@kus could you please check your gungame-db.json? I think it may be in an error with it according to your log.
Here is my file:
`{
  "StatsDB": {
    "DatabaseType": "SQLite",
    "DatabaseFilePath": "/csgo/cfg/gungame-db.sqlite",
    "GeoDatabaseFilePath": "/csgo/cfg/GeoLite2-Country.mmdb",
    "DatabaseHost": "your_mysql_host",
    "DatabasePort": 3306,
    "DatabaseUser": "your_mysql_username",
    "DatabasePassword": "your_mysql_password",
    "DatabaseName": "your_mysql_database",
    "Comment": "use SQLite or MySQL as Database Type"
  },
  "OnlineDB": {
    "DatabaseType": "MySQL",
    "DatabaseFilePath": "",
    "GeoDatabaseFilePath": "",
    "DatabaseHost": "your_mysql_host",
    "DatabasePort": 3306,
    "DatabaseUser": "your_mysql_username",
    "DatabasePassword": "your_mysql_password",
    "DatabaseName": "your_mysql_database",
    "Comment": "use MySQL only as Database Type"
  }
}`

**Comment by kus** [comment]
@ssypchenko ahhh did you change the format of `gungame-db.json` ?

Before it was:

```
{
  "DatabaseType": "SQLite",
  "DatabaseFilePath": "/csgo/cfg/gungame-db.sqlite"
}
```

If that's the case, that will definately be the culprit.

If you make breaking changes like that, when loading the config check if `config.StatsDB` doesn't exist throw an error saying to update the config to the new format so it's clearer and would save you less tickets :)

So if I'm only using SQLite will my file be:

```
{
  "StatsDB": {
    "DatabaseType": "SQLite",
    "DatabaseFilePath": "/csgo/cfg/gungame-db.sqlite",
    "GeoDatabaseFilePath": "/csgo/cfg/GeoLite2-Country.mmdb",
  }
}
```

Also if you are doing updates to the table schemas it would be nice if the plugin checks if a column doesn't exist and runs the `ALTER` command for you.

**Comment by ssypchenko** [comment]
> config.StatsDB

I've added checks for StatsDB in the code for the new versions. And I'll try to add other suggestions too :)

**Comment by kus** [comment]
Great thanks!

Updating `gungame-db.json` to the below has fixed the issue!

```
{
  "StatsDB": {
    "DatabaseType": "SQLite",
    "DatabaseFilePath": "/csgo/cfg/gungame-db.sqlite",
    "GeoDatabaseFilePath": "/csgo/cfg/GeoLite2-Country.mmdb",
  }
}
```

I do get this error, but the server doesn't crash so assume it's fine. Just saying that I'm not using MySQL.

`[GunGame_Online - FATAL] InitializeDatabaseConnection: Database connection error: Object reference not set to an instance of an object., working without online reports`

Thanks for your help, and thanks for your great plugin! GunGame was the one thing I missed moving from CS:GO to CS2.
